# production:
#  adapter: mysql2
#  pool: 5 
#  database: xema_production
#  username: root
#  password: root


development:
  adapter: postgresql
  encoding: unicode
  database: my_xema1
  host: localhost
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: my_xema1
  host: localhost
  pool: 5
  username: postgres
  password: root
production:
  adapter: postgresql
  encoding: unicode
  database: mycustomerfeedback
  host: localhost
  pool: 5
  username: postgres
  password: root
